services:

  postgres-auth:
    image: postgres:16-alpine
    container_name: postgres-auth
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U auth_user -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  mysql-reserva:
    image: mysql:8.4
    container_name: mysql-reserva
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: reserva_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_reserva_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h localhost -u root -proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  postgres_auth_data:
  mysql_reserva_data:
